:concurrency: 5
:queues:
  - [active_storage_analysis,2]
  - [active_storage_purge,2]
  - [block_user, 2]
  - [decidim_events, 2]
  - [default, 2]
  - [events, 2]
  - [exports,1]
  - [mailers, 4]
  - [metrics, 1]
  - [newsletter, 2]
  - [newsletters_opt_in, 2]
  - [conference_diplomas, 2]
  - [user_report, 2]